import React, { useState, useEffect } from 'react';
import confetti from 'canvas-confetti';
import { 
  Sparkles, Camera, MapPin, CheckCircle2, AlertTriangle, 
  ArrowRight, ArrowLeft, Upload, RefreshCw, ThumbsUp, 
  Building2, Check, FileText, Crosshair 
} from 'lucide-react';
import { InteractiveMap } from '../components/InteractiveMap';
import { PriorityBadge } from '../components/PriorityBadge';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';
import { IssuePriority, Category, Department, CivicIssue } from '../types';

interface ReportWizardViewProps {
  onSuccess: (issueId: string) => void;
  onCancel: () => void;
}

export const ReportWizardView: React.FC<ReportWizardViewProps> = ({ onSuccess, onCancel }) => {
  const { user, showToast } = useAuth();

  // Wizard Step: 1 = Description, 2 = Evidence, 3 = Location, 4 = AI Analysis & Duplicates, 5 = Review
  const [currentStep, setCurrentStep] = useState<number>(1);

  // Form State - Starts empty for authentic user input
  const [rawPrompt, setRawPrompt] = useState('');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('');
  const [priority, setPriority] = useState<IssuePriority>('HIGH');
  const [departmentId, setDepartmentId] = useState('');
  const [address, setAddress] = useState('');
  const [landmark, setLandmark] = useState('');
  const [coordinates, setCoordinates] = useState({ lat: 12.9716, lng: 77.5946 });
  const [imageUrl, setImageUrl] = useState('');
  const [imageCaption, setImageCaption] = useState('');

  // Metadata
  const [categories, setCategories] = useState<Category[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);

  // AI & Duplicate state
  const [aiAssistantLoading, setAiAssistantLoading] = useState(false);
  const [aiAnalysisLoading, setAiAnalysisLoading] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);
  const [duplicateCheck, setDuplicateCheck] = useState<{
    isPotentialDuplicate: boolean;
    duplicateCandidate?: CivicIssue;
    distanceMeters?: number;
    matchScore?: number;
  } | null>(null);

  // Submission state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submittedIssue, setSubmittedIssue] = useState<CivicIssue | null>(null);

  useEffect(() => {
    api.getCategories().then((cats) => {
      setCategories(cats);
      if (cats.length > 0 && !category) {
        setCategory(cats[0].name);
        setDepartmentId(cats[0].departmentId);
      }
    }).catch(() => {});

    api.getDepartments().then(setDepartments).catch(() => {});
  }, []);

  // AI Description Assistant
  const handleAIAssistDescription = async () => {
    if (!rawPrompt.trim()) {
      showToast('Enter a brief phrase first (e.g. "big pothole near bus stop")', 'info');
      return;
    }
    try {
      setAiAssistantLoading(true);
      const res = await api.assistDescription(rawPrompt);
      setTitle(res.title);
      setDescription(res.description);
      if (res.category) {
        setCategory(res.category);
        const matchDept = categories.find(c => c.name.toLowerCase() === res.category.toLowerCase());
        if (matchDept) setDepartmentId(matchDept.departmentId);
      }
      if (res.suggestedPriority) setPriority(res.suggestedPriority);
      showToast('Formal title & description generated by AI', 'success');
    } catch (err: any) {
      showToast(err.message || 'AI assistant unavailable', 'error');
    } finally {
      setAiAssistantLoading(false);
    }
  };

  // Run AI Analysis & Duplicate Check on Step 4
  const runAiAnalysisAndDuplicateCheck = async () => {
    try {
      setAiAnalysisLoading(true);
      // Run Vision or description analysis
      if (imageUrl) {
        const analysis = await api.analyzeImage(imageUrl, description || title);
        setAiAnalysis(analysis);
        setCategory(analysis.category);
        setPriority(analysis.suggestedSeverity);
        const dept = departments.find(d => d.name.toLowerCase() === analysis.suggestedDepartment.toLowerCase());
        if (dept) setDepartmentId(dept.id);
      }

      // Run Duplicate Check
      const dup = await api.checkDuplicates(coordinates.lat, coordinates.lng, category || 'Road Damage & Potholes');
      setDuplicateCheck(dup);
    } catch (e) {
      console.warn('AI analysis error:', e);
    } finally {
      setAiAnalysisLoading(false);
    }
  };

  const handleNextStep = () => {
    if (currentStep === 1) {
      if (!title.trim() || !description.trim()) {
        showToast('Please provide a title and description', 'error');
        return;
      }
    }
    if (currentStep === 3) {
      // Moving to Step 4: run AI analysis
      runAiAnalysisAndDuplicateCheck();
    }
    setCurrentStep((prev) => Math.min(prev + 1, 5));
  };

  const handlePrevStep = () => {
    setCurrentStep((prev) => Math.max(prev - 1, 1));
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      showToast('Only image files (JPEG, PNG, WEBP) are supported', 'error');
      return;
    }

    if (file.size > 10 * 1024 * 1024) {
      showToast('Image size cannot exceed 10MB', 'error');
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      setImageUrl(reader.result as string);
      showToast('Image uploaded successfully');
    };
    reader.readAsDataURL(file);
  };

  const handleSubmitReport = async () => {
    try {
      setIsSubmitting(true);
      const newIssue = await api.createIssue({
        title,
        description,
        category: category || (categories[0]?.name || 'Road Damage & Potholes'),
        priority,
        latitude: coordinates.lat,
        longitude: coordinates.lng,
        address: address || `Coordinates: ${coordinates.lat.toFixed(4)}, ${coordinates.lng.toFixed(4)}`,
        landmark,
        departmentId: departmentId || (departments[0]?.id),
        images: imageUrl ? [
          {
            url: imageUrl,
            type: 'EVIDENCE',
            caption: imageCaption || 'Citizen reported evidence',
          }
        ] : [],
        aiAnalysis,
      });

      confetti({
        particleCount: 100,
        spread: 80,
        origin: { y: 0.6 },
      });

      setSubmittedIssue(newIssue);
      showToast(`Civic report ${newIssue.publicId} submitted!`, 'success');
    } catch (err: any) {
      showToast(err.message || 'Submission failed', 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  // SUCCESS SCREEN
  if (submittedIssue) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12 text-center animate-in zoom-in-95">
        <div className="w-16 h-16 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-600 flex items-center justify-center mx-auto mb-6 shadow-inner">
          <CheckCircle2 className="w-10 h-10" />
        </div>

        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">
          Report Submitted Successfully!
        </h2>
        <p className="text-sm text-slate-600 dark:text-slate-400 mt-2">
          Your civic issue has been logged, assigned an SLA deadline, and dispatched to the municipal queue.
        </p>

        {/* CivicFix Ticket Card */}
        <div className="mt-8 p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl text-left space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
              CivicFix Tracking ID
            </span>
            <span className="font-mono text-base font-black px-3 py-1 rounded-xl bg-sky-50 dark:bg-sky-950 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800">
              {submittedIssue.publicId}
            </span>
          </div>

          <div className="grid grid-cols-2 gap-4 text-xs">
            <div>
              <span className="text-slate-400 font-semibold">Category:</span>
              <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5">
                {submittedIssue.category}
              </div>
            </div>
            <div>
              <span className="text-slate-400 font-semibold">Initial Priority:</span>
              <div className="mt-0.5">
                <PriorityBadge priority={submittedIssue.priority} size="sm" />
              </div>
            </div>
            <div>
              <span className="text-slate-400 font-semibold">Location:</span>
              <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5 truncate">
                {submittedIssue.address}
              </div>
            </div>
            <div>
              <span className="text-slate-400 font-semibold">Department:</span>
              <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5">
                {submittedIssue.departmentName}
              </div>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/40 text-xs text-slate-500 flex items-center justify-between">
            <span>SLA Target Deadline:</span>
            <span className="font-bold text-slate-700 dark:text-slate-300">
              {new Date(submittedIssue.slaDeadline).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}
            </span>
          </div>
        </div>

        <div className="flex flex-wrap items-center justify-center gap-3 mt-8">
          <button
            onClick={() => onSuccess(submittedIssue.id)}
            className="px-6 py-3 rounded-2xl bg-sky-600 hover:bg-sky-700 text-white font-bold text-xs shadow-lg shadow-sky-600/30 flex items-center gap-2"
          >
            <span>Track This Report</span>
            <ArrowRight className="w-4 h-4" />
          </button>
          <button
            onClick={() => {
              setSubmittedIssue(null);
              setCurrentStep(1);
              setTitle('');
              setDescription('');
              setRawPrompt('');
            }}
            className="px-6 py-3 rounded-2xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold text-xs"
          >
            Submit Another Problem
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      {/* Wizard Progress Stepper */}
      <div className="mb-8">
        <div className="flex items-center justify-between text-xs font-semibold text-slate-400 mb-2">
          <span>Step {currentStep} of 5</span>
          <span>
            {currentStep === 1 && 'Problem Description'}
            {currentStep === 2 && 'Upload Evidence'}
            {currentStep === 3 && 'Location Pinpoint'}
            {currentStep === 4 && 'AI Triage & Duplicates'}
            {currentStep === 5 && 'Review & Submit'}
          </span>
        </div>
        <div className="w-full h-2 rounded-full bg-slate-200 dark:bg-slate-800 overflow-hidden">
          <div
            className="h-full bg-sky-600 transition-all duration-300 rounded-full"
            style={{ width: `${(currentStep / 5) * 100}%` }}
          />
        </div>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden p-6 sm:p-8 space-y-6">

        {/* STEP 1: DESCRIPTION & AI ASSISTANT */}
        {currentStep === 1 && (
          <div className="space-y-6 animate-in fade-in">
            <div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                Describe the Civic Problem
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                You can write a quick note or speak, and our AI Assistant will refine it into a formal municipal complaint.
              </p>
            </div>

            {/* Quick Prompt & AI Generate Button */}
            <div className="p-4 rounded-2xl bg-sky-50/70 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-800 space-y-3">
              <label className="text-xs font-bold text-sky-900 dark:text-sky-300 flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5" />
                Quick Note / Voice-to-Text Helper
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder='e.g. "big pothole near bus stop spilling water"'
                  value={rawPrompt}
                  onChange={(e) => setRawPrompt(e.target.value)}
                  className="flex-1 p-2.5 text-xs rounded-xl border border-sky-300 dark:border-sky-700 bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-200"
                />
                <button
                  type="button"
                  onClick={handleAIAssistDescription}
                  disabled={aiAssistantLoading}
                  className="px-4 py-2.5 bg-sky-600 hover:bg-sky-700 text-white font-bold text-xs rounded-xl flex items-center gap-1.5 disabled:opacity-50 shrink-0 shadow-sm"
                >
                  <Sparkles className={`w-3.5 h-3.5 ${aiAssistantLoading ? 'animate-spin' : ''}`} />
                  {aiAssistantLoading ? 'Drafting...' : 'Refine with AI'}
                </button>
              </div>
            </div>

            {/* Formal Title Input */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Issue Title *
              </label>
              <input
                type="text"
                placeholder="Concise summary (e.g. Large Hazardous Pothole on Market St)"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                required
                className="w-full p-3 text-sm rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
              />
            </div>

            {/* Detailed Description Input */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Detailed Description *
              </label>
              <textarea
                placeholder="Describe what you observed, potential hazards to cars or pedestrians, and any relevant details..."
                rows={4}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                required
                className="w-full p-3 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200 leading-relaxed"
              />
            </div>
          </div>
        )}

        {/* STEP 2: EVIDENCE UPLOAD */}
        {currentStep === 2 && (
          <div className="space-y-6 animate-in fade-in">
            <div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                Upload Photo Evidence
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                Visual proof enables faster AI severity scoring and equips field workers with proper tools.
              </p>
            </div>

            {/* File Drag/Drop or picker */}
            <div className="border-2 border-dashed border-slate-300 dark:border-slate-700 rounded-3xl p-6 text-center space-y-3 bg-slate-50 dark:bg-slate-800/30">
              <div className="w-12 h-12 rounded-2xl bg-sky-100 dark:bg-sky-950 text-sky-600 flex items-center justify-center mx-auto">
                <Upload className="w-6 h-6" />
              </div>
              <div className="text-xs text-slate-600 dark:text-slate-400">
                <label className="font-bold text-sky-600 dark:text-sky-400 hover:underline cursor-pointer">
                  Choose a file
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                </label>{' '}
                or drag and drop here (JPG, PNG, WebP up to 10MB)
              </div>
              <div className="text-[11px] text-slate-400">
                Or paste an image URL below:
              </div>
              <input
                type="url"
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
                placeholder="https://images.unsplash.com/..."
                className="w-full max-w-md mx-auto p-2 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
              />
            </div>

            {/* Preview Card */}
            {imageUrl && (
              <div className="p-4 rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 flex gap-4 items-center">
                <img
                  src={imageUrl}
                  alt="Preview"
                  className="w-24 h-24 rounded-xl object-cover shrink-0 border border-slate-200 dark:border-slate-700"
                />
                <div className="flex-1 space-y-1.5">
                  <span className="text-[11px] font-bold uppercase text-emerald-600 dark:text-emerald-400 flex items-center gap-1">
                    <Check className="w-3.5 h-3.5" /> Evidence Attached
                  </span>
                  <input
                    type="text"
                    placeholder="Add brief caption (e.g. Broken pavement in right lane)"
                    value={imageCaption}
                    onChange={(e) => setImageCaption(e.target.value)}
                    className="w-full p-2 text-xs rounded-lg border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800"
                  />
                </div>
              </div>
            )}
          </div>
        )}

        {/* STEP 3: LOCATION PINPOINT */}
        {currentStep === 3 && (
          <div className="space-y-6 animate-in fade-in">
            <div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                Pinpoint Location
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                Drop a pin on the exact location of the issue. You can drag the red marker or use your device GPS.
              </p>
            </div>

            {/* Map Picker */}
            <div className="h-72 w-full rounded-2xl overflow-hidden border border-slate-200 dark:border-slate-800">
              <InteractiveMap
                pickerMode={true}
                pickerCoordinates={coordinates}
                onCoordinatesChange={setCoordinates}
                height="288px"
                initialCenter={[coordinates.lat, coordinates.lng]}
                zoom={14}
              />
            </div>

            {/* Bengaluru Neighborhood Quick Selection */}
            <div className="space-y-1.5">
              <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                Quick Select Bengaluru Neighborhood:
              </span>
              <div className="flex flex-wrap gap-1.5">
                {[
                  { name: 'Koramangala 4th Block', lat: 12.9352, lng: 77.6245, addr: '80 Feet Rd, 4th Block, Koramangala, Bengaluru 560034' },
                  { name: 'Indiranagar 100ft Rd', lat: 12.9784, lng: 77.6408, addr: '100 Feet Rd, HAL 2nd Stage, Indiranagar, Bengaluru 560038' },
                  { name: 'MG Road / Brigade Rd', lat: 12.9748, lng: 77.6080, addr: 'MG Road & Brigade Rd Junction, Bengaluru 560001' },
                  { name: 'Whitefield ITPL', lat: 12.9698, lng: 77.7499, addr: 'ITPL Main Rd, Whitefield, Bengaluru 560066' },
                  { name: 'HSR Layout 27th Main', lat: 12.9121, lng: 77.6446, addr: '27th Main Rd, Sector 1, HSR Layout, Bengaluru 560102' },
                  { name: 'Malleshwaram 8th Cross', lat: 13.0031, lng: 77.5643, addr: 'Sampige Rd, 8th Cross, Malleshwaram, Bengaluru 560003' },
                  { name: 'Jayanagar 4th Block', lat: 12.9308, lng: 77.5838, addr: '11th Main Rd, 4th Block, Jayanagar, Bengaluru 560011' },
                  { name: 'Bellandur ORR', lat: 12.9260, lng: 77.6762, addr: 'Outer Ring Rd, Green Glen Layout, Bellandur, Bengaluru 560103' },
                ].map((item, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => {
                      setCoordinates({ lat: item.lat, lng: item.lng });
                      setAddress(item.addr);
                    }}
                    className="px-2.5 py-1 text-[11px] font-semibold rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition-colors"
                  >
                    📍 {item.name}
                  </button>
                ))}
              </div>
            </div>

            {/* Location & Landmark Inputs */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                  Street Address *
                </label>
                <input
                  type="text"
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  placeholder="Street name or nearby building"
                  required
                  className="w-full p-2.5 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                />
              </div>
              <div className="space-y-1">
                <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                  Landmark / Reference
                </label>
                <input
                  type="text"
                  value={landmark}
                  onChange={(e) => setLandmark(e.target.value)}
                  placeholder="e.g. Opposite blue cafe, outside subway entrance"
                  className="w-full p-2.5 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200"
                />
              </div>
            </div>

            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/40 text-[11px] text-slate-500 flex items-center justify-between">
              <span>Selected Coordinates:</span>
              <span className="font-mono font-bold text-slate-700 dark:text-slate-300">
                {coordinates.lat.toFixed(5)}, {coordinates.lng.toFixed(5)}
              </span>
            </div>
          </div>
        )}

        {/* STEP 4: AI ANALYSIS & DUPLICATE CHECK */}
        {currentStep === 4 && (
          <div className="space-y-6 animate-in fade-in">
            <div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-sky-600" />
                AI Triage & Duplicate Protection
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                Automated municipal intelligence classifies category, assigns severity, and verifies nearby tickets to prevent duplicate dispatch.
              </p>
            </div>

            {aiAnalysisLoading ? (
              <div className="p-12 text-center space-y-3">
                <div className="w-10 h-10 border-4 border-sky-600 border-t-transparent rounded-full animate-spin mx-auto" />
                <p className="text-xs font-semibold text-slate-500">
                  Analyzing image features, category semantics, and checking geo-proximity...
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                {/* Duplicate Banner if candidate found */}
                {duplicateCheck?.isPotentialDuplicate && duplicateCheck.duplicateCandidate && (
                  <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800 space-y-3">
                    <div className="flex items-start gap-3">
                      <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                      <div className="flex-1">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-bold text-amber-900 dark:text-amber-300">
                            Potential Duplicate Found ({duplicateCheck.distanceMeters}m away)
                          </span>
                          <span className="font-mono text-[10px] font-bold bg-amber-200 dark:bg-amber-900 px-2 py-0.5 rounded">
                            {duplicateCheck.duplicateCandidate.publicId}
                          </span>
                        </div>
                        <p className="text-xs text-amber-800 dark:text-amber-200 mt-1">
                          "{duplicateCheck.duplicateCandidate.title}"
                        </p>
                        <p className="text-[11px] text-amber-700/80 dark:text-amber-300/80 mt-0.5">
                          Status: {duplicateCheck.duplicateCandidate.status} • {duplicateCheck.duplicateCandidate.upvotesCount} citizens already affected
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 pt-1">
                      <button
                        type="button"
                        onClick={() => {
                          api.toggleUpvote(duplicateCheck.duplicateCandidate!.id);
                          showToast('You endorsed the existing report! Discarding duplicate.');
                          onSuccess(duplicateCheck.duplicateCandidate!.id);
                        }}
                        className="px-3 py-1.5 rounded-lg bg-amber-600 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm"
                      >
                        <ThumbsUp className="w-3.5 h-3.5" />
                        Support Existing Report Instead
                      </button>
                      <button
                        type="button"
                        onClick={() => setDuplicateCheck(null)}
                        className="px-3 py-1.5 text-xs text-amber-700 dark:text-amber-300 font-semibold hover:underline"
                      >
                        Continue as New Report
                      </button>
                    </div>
                  </div>
                )}

                {/* AI Classification Summary */}
                {aiAnalysis && (
                  <div className="p-5 rounded-2xl bg-sky-50 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-800 space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold uppercase tracking-wider text-sky-900 dark:text-sky-300">
                        AI Suggested Classification
                      </span>
                      <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-sky-200 dark:bg-sky-900 text-sky-800 dark:text-sky-200">
                        {aiAnalysis.confidence}% Confidence
                      </span>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                      <div>
                        <span className="text-slate-500 font-semibold">Category:</span>
                        <select
                          value={category}
                          onChange={(e) => setCategory(e.target.value)}
                          className="mt-1 w-full p-2 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800"
                        >
                          {categories.map((c) => (
                            <option key={c.id} value={c.name}>
                              {c.name}
                            </option>
                          ))}
                        </select>
                      </div>

                      <div>
                        <span className="text-slate-500 font-semibold">Suggested Severity:</span>
                        <select
                          value={priority}
                          onChange={(e) => setPriority(e.target.value as any)}
                          className="mt-1 w-full p-2 text-xs rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800"
                        >
                          <option value="CRITICAL">Critical</option>
                          <option value="HIGH">High</option>
                          <option value="MEDIUM">Medium</option>
                          <option value="LOW">Low</option>
                        </select>
                      </div>
                    </div>

                    <div className="text-xs text-slate-700 dark:text-slate-300 bg-white/70 dark:bg-slate-900/70 p-3 rounded-xl border border-sky-100 dark:border-sky-900/60 leading-relaxed">
                      <span className="font-bold text-sky-800 dark:text-sky-400">AI Reasoning: </span>
                      {aiAnalysis.reasoningSummary}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* STEP 5: REVIEW & CONFIRM */}
        {currentStep === 5 && (
          <div className="space-y-6 animate-in fade-in">
            <div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                Review & Confirm
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                Please verify all details before submitting to municipal dispatch.
              </p>
            </div>

            <div className="p-5 rounded-2xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/30 space-y-4 text-xs">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <div className="text-base font-bold text-slate-900 dark:text-white">
                    {title}
                  </div>
                  <p className="text-slate-600 dark:text-slate-400 mt-1 leading-relaxed">
                    {description}
                  </p>
                </div>
                <PriorityBadge priority={priority} />
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 pt-3 border-t border-slate-200 dark:border-slate-700/60">
                <div>
                  <span className="text-slate-400 font-semibold">Category:</span>
                  <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5">
                    {category}
                  </div>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold">Location:</span>
                  <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5 truncate">
                    {address}
                  </div>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold">Reporter:</span>
                  <div className="font-bold text-slate-800 dark:text-slate-200 mt-0.5">
                    {user?.name || 'Citizen'}
                  </div>
                </div>
              </div>

              {imageUrl && (
                <div className="pt-2">
                  <span className="text-slate-400 font-semibold block mb-1.5">Attached Photo:</span>
                  <img
                    src={imageUrl}
                    alt="Preview"
                    className="w-32 h-20 rounded-xl object-cover border border-slate-200 dark:border-slate-700"
                  />
                </div>
              )}
            </div>
          </div>
        )}

        {/* Action Controls */}
        <div className="flex items-center justify-between pt-4 border-t border-slate-100 dark:border-slate-800">
          {currentStep > 1 ? (
            <button
              type="button"
              onClick={handlePrevStep}
              className="px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-bold text-xs flex items-center gap-1.5 hover:bg-slate-50 dark:hover:bg-slate-800"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              Previous
            </button>
          ) : (
            <button
              type="button"
              onClick={onCancel}
              className="px-4 py-2.5 text-xs text-slate-400 hover:text-slate-600 font-semibold"
            >
              Cancel
            </button>
          )}

          {currentStep < 5 ? (
            <button
              type="button"
              onClick={handleNextStep}
              className="px-5 py-2.5 rounded-xl bg-sky-600 hover:bg-sky-700 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm shadow-sky-600/30"
            >
              Next Step
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          ) : (
            <button
              type="button"
              onClick={handleSubmitReport}
              disabled={isSubmitting}
              className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs flex items-center gap-1.5 shadow-md shadow-emerald-600/30 disabled:opacity-50"
            >
              {isSubmitting ? 'Submitting...' : 'Submit Civic Report'}
              <Check className="w-4 h-4" />
            </button>
          )}
        </div>

      </div>
    </div>
  );
};
